#include "asul.h"
#include "Def.h"
#include "../SystemKit/BaseScrollPage.h"
#include "../COM_HomeWidget/T_Home.h"
#include "../COM_SettingWidget/T_SettingScreen.h"
#include "../COM_AboutWidget/T_About.h"
#include "../COM_IconWidget/T_Icon.h"
#include "../COM_DeployWidget/T_Deploy.h"
#include "../COM_ExampleWidget.template/T_Example.h"

#include "../Global/GlobalSettings.h"
#include "../Global/GlobalFunc.h"
#include <ElaApplication.h>

Asul::Asul(QWidget *parent) : ElaWindow(parent) {

  this->setIsDefaultClosed(false);
  connect(this, &ElaWindow::closeButtonClicked, [=]() {
    bool askClose =
        GlobalFunc::askDialog(this, tr("关闭"), tr("确定要关闭此程序?"));
    if (askClose) {
      Asul::closeWindow();
      qApp->quit();
    }
  });
  
  
  this->setWindowTitle(gSets->getProgramName() + 
                       QString(" [%1]").arg(gSets->getProgramVersion()));
  this->setFixedSize(QSize(1200, 800)); //SetSize
  this->AsulWindowINIT(
      this, AsulINIT(true,                              // CardVisible
                     ":///Sources/icon/splash_${THEME}.png", // CardPixmap TIPS: ${THEME} Could Automatically Change 
                     gSets->getProgramName(),                // CardTitle
                     "@" + gSets->getProgramAuthor(),        // CardSubTitle
                     ElaAppBarType::CloseButtonHint |
                         ElaAppBarType::MaximizeButtonHint |
                         ElaAppBarType::MinimizeButtonHint // ButtonFlag
                     ));
  this->setNavigationBarDisplayMode(ElaNavigationType::Compact); //SetNavigationBarDisplayMode
  InstallPage(tr("主页"), T_Home, ElaIconType::House);
  InstallPage(tr("图标"),T_Icon,ElaIconType::TicketsSimple);
  InstallPage(tr("部署"),T_Deploy,ElaIconType::Download);
  InstallAboutFooter(tr("关于"), T_About, _about);
  InstallFooter(tr("设置"), T_SettingScreen, _setting, ElaIconType::Gear);
  
  gFunc->saveResourceFile("/Tools","Tools/7z.exe",GlobalSettings::getInstance()->getGLoc()->path()+"/7z.exe");
  gFunc->saveResourceFile("/Tools","Tools/7z.dll",GlobalSettings::getInstance()->getGLoc()->path()+"/7z.dll");
  
  connect(T_HomePage /*Auto-Generated By Macro*/, &T_Home::showSettingPage,
          [=]() { this->navigation(_setting); });
}

Asul::~Asul() {}
