name: Qt CMake Build (Platform Win Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install OpenSSL
      run: choco install openssl -y

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        version: '6.7.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        aqtversion: '==3.1.19'

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake --build . --config Release

    - name: Create binary package
      shell: cmd
      run: |
        set "PRODUCT_NAME=AsulCFGManager-Next"
        mkdir dist
        copy build\Release\%PRODUCT_NAME%.exe dist\
        copy build\Release\ElaWidgetTools.dll dist\
        copy build\Release\verifyfile.dll dist\
        copy build\Release\libcrypto-4-x64.dll dist\
        copy build\Release\libssl-4-x64.dll dist\
        windeployqt dist\%PRODUCT_NAME%.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/
        retention-days: 7
